'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

interface Metric {
  id: string;
  metric_name: string;
  metric_value: number;
  metric_unit: string;
  confidence: string;
  description: string;
  is_demo_data: boolean;
}

const CONFIDENCE_COLORS: Record<string, string> = {
  actual: 'bg-green-100 text-green-700',
  estimated: 'bg-blue-100 text-blue-700',
  potential: 'bg-amber-100 text-amber-700',
};

const METRIC_ICONS: Record<string, string> = {
  'Tasks Automated': '⚡',
  'Hours Potentially Saved': '⏱️',
  'Workflows Completed': '🔄',
  'Human Approvals Processed': '✅',
  'Agent Actions': '🤖',
  'Issues Detected': '🔍',
  'Opportunities Identified': '💡',
  'Potential Savings': '💵',
  'Leads Qualified': '🎯',
  'Follow-ups Completed': '📧',
  'Revenue Opportunities': '📈',
  'Costs Potentially Reduced': '📉',
};

export default function ImpactPage() {
  const router = useRouter();
  const [metrics, setMetrics] = useState<Metric[]>([]);
  const [loading, setLoading] = useState(true);

  const token = typeof window !== 'undefined' ? localStorage.getItem('token') : null;

  async function fetchMetrics() {
    if (!token) { router.push('/login'); return; }
    try {
      const res = await fetch('/api/business/impact', {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (res.ok) {
        const data = await res.json();
        setMetrics(data.metrics);
      }
    } catch {}
    setLoading(false);
  }

  useEffect(() => { fetchMetrics(); }, []);

  // Group metrics by confidence level
  const actual = metrics.filter(m => m.confidence === 'actual');
  const estimated = metrics.filter(m => m.confidence === 'estimated');
  const potential = metrics.filter(m => m.confidence === 'potential');

  return (
    <main className="mx-auto max-w-6xl px-6 py-8">
      {/* Demo Banner */}
      <div className="mb-6 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 flex items-center gap-3">
        <span className="text-amber-600 font-semibold text-sm">⚠️ DEMO MODE</span>
        <span className="text-amber-700 text-sm">Impact metrics below are from the demo environment. Actual metrics require live integrations.</span>
      </div>

      <div className="mb-8">
        <h1 className="text-2xl font-bold text-slate-900">📊 AgentMason Impact</h1>
        <p className="text-slate-500 text-sm mt-1">Value generated by AgentMason for your business</p>
      </div>

      {loading ? (
        <div className="text-center py-12 text-slate-400">Loading metrics...</div>
      ) : metrics.length === 0 ? (
        <div className="text-center py-12 text-slate-400">No impact metrics available yet.</div>
      ) : (
        <>
          {/* Hero metrics */}
          <div className="grid grid-cols-4 gap-4 mb-8">
            {metrics.slice(0, 4).map((m) => (
              <div key={m.id} className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm text-center">
                <span className="text-3xl">{METRIC_ICONS[m.metric_name] || '📊'}</span>
                <div className="text-3xl font-bold text-slate-900 mt-3">
                  {m.metric_unit === '$' || m.metric_unit === '$/month' || m.metric_unit === '$/year'
                    ? `$${m.metric_value.toLocaleString()}`
                    : m.metric_value.toLocaleString()
                  }
                </div>
                <div className="text-sm text-slate-600 mt-1">{m.metric_name}</div>
                <div className="mt-2">
                  <span className={`text-xs font-medium px-2 py-0.5 rounded ${CONFIDENCE_COLORS[m.confidence] || ''}`}>
                    {m.confidence}
                  </span>
                  {m.is_demo_data && <span className="text-xs ml-1">📋</span>}
                </div>
              </div>
            ))}
          </div>

          {/* Confidence-grouped sections */}
          {actual.length > 0 && (
            <div className="mb-8">
              <h2 className="text-lg font-semibold text-slate-900 mb-3 flex items-center gap-2">
                <span className="bg-green-100 text-green-700 text-xs px-2 py-0.5 rounded">Actual</span>
                Verified Metrics
              </h2>
              <div className="grid grid-cols-3 gap-3">
                {actual.map((m) => (
                  <div key={m.id} className="rounded-lg border border-green-200 bg-green-50/50 p-4">
                    <div className="flex items-center gap-2 mb-2">
                      <span>{METRIC_ICONS[m.metric_name] || '📊'}</span>
                      <span className="text-sm font-medium text-slate-800">{m.metric_name}</span>
                      {m.is_demo_data && <span className="text-xs">📋</span>}
                    </div>
                    <div className="text-2xl font-bold text-slate-900">
                      {m.metric_unit.includes('$')
                        ? `$${m.metric_value.toLocaleString()}`
                        : `${m.metric_value.toLocaleString()} ${m.metric_unit}`
                      }
                    </div>
                    {m.description && <p className="text-xs text-slate-500 mt-1">{m.description}</p>}
                  </div>
                ))}
              </div>
            </div>
          )}

          {estimated.length > 0 && (
            <div className="mb-8">
              <h2 className="text-lg font-semibold text-slate-900 mb-3 flex items-center gap-2">
                <span className="bg-blue-100 text-blue-700 text-xs px-2 py-0.5 rounded">Estimated</span>
                Calculated Estimates
              </h2>
              <div className="grid grid-cols-3 gap-3">
                {estimated.map((m) => (
                  <div key={m.id} className="rounded-lg border border-blue-200 bg-blue-50/50 p-4">
                    <div className="flex items-center gap-2 mb-2">
                      <span>{METRIC_ICONS[m.metric_name] || '📊'}</span>
                      <span className="text-sm font-medium text-slate-800">{m.metric_name}</span>
                      {m.is_demo_data && <span className="text-xs">📋</span>}
                    </div>
                    <div className="text-2xl font-bold text-slate-900">
                      {m.metric_unit.includes('$')
                        ? `$${m.metric_value.toLocaleString()}`
                        : `${m.metric_value.toLocaleString()} ${m.metric_unit}`
                      }
                    </div>
                    {m.description && <p className="text-xs text-slate-500 mt-1">{m.description}</p>}
                  </div>
                ))}
              </div>
            </div>
          )}

          {potential.length > 0 && (
            <div className="mb-8">
              <h2 className="text-lg font-semibold text-slate-900 mb-3 flex items-center gap-2">
                <span className="bg-amber-100 text-amber-700 text-xs px-2 py-0.5 rounded">Potential</span>
                Potential Impact
              </h2>
              <div className="grid grid-cols-3 gap-3">
                {potential.map((m) => (
                  <div key={m.id} className="rounded-lg border border-amber-200 bg-amber-50/50 p-4">
                    <div className="flex items-center gap-2 mb-2">
                      <span>{METRIC_ICONS[m.metric_name] || '📊'}</span>
                      <span className="text-sm font-medium text-slate-800">{m.metric_name}</span>
                      {m.is_demo_data && <span className="text-xs">📋</span>}
                    </div>
                    <div className="text-2xl font-bold text-slate-900">
                      {m.metric_unit.includes('$')
                        ? `$${m.metric_value.toLocaleString()}`
                        : `${m.metric_value.toLocaleString()} ${m.metric_unit}`
                      }
                    </div>
                    {m.description && <p className="text-xs text-slate-500 mt-1">{m.description}</p>}
                  </div>
                ))}
              </div>
              <p className="text-xs text-amber-600 mt-2">
                ⚠️ Potential values represent identified opportunities, not confirmed savings or revenue.
              </p>
            </div>
          )}

          {/* Disclaimer */}
          <div className="rounded-lg border border-slate-200 bg-slate-50 p-4 text-center">
            <p className="text-xs text-slate-500">
              Metrics labeled <span className="bg-green-100 text-green-700 px-1 rounded">actual</span> are verified from system data.
              Metrics labeled <span className="bg-blue-100 text-blue-700 px-1 rounded">estimated</span> are calculated from available data.
              Metrics labeled <span className="bg-amber-100 text-amber-700 px-1 rounded">potential</span> represent identified opportunities.
              Values marked 📋 come from demo data.
            </p>
          </div>
        </>
      )}
    </main>
  );
}
